pub struct State {}

impl Default for State {
    fn default() -> Self {
        State {}
    }
}

impl State {
    pub fn on_packet<'a>(
        &mut self,
        iph: etherparse::Ipv4HeaderSlice<'a>,
        tcph: etherparse::TcpHeaderSlice<'a>,
        data: &'a [u8],
    ) {
        eprintln!(
            "{}:{} -> {}:{} {:?}, {} bytes = {:x?}",
            iph.source_addr(),
            tcph.source_port(),
            iph.destination_addr(),
            tcph.destination_port(),
            ip_number_from_u8(iph.protocol()),
            data.len(),
            &data,
        );
    }
}

pub fn ip_number_from_u8(value: u8) -> etherparse::IpNumber {
    match value {
        0 => etherparse::IpNumber::IPv6HeaderHopByHop,
        1 => etherparse::IpNumber::Icmp,
        2 => etherparse::IpNumber::Igmp,
        3 => etherparse::IpNumber::Ggp,
        4 => etherparse::IpNumber::IPv4,
        5 => etherparse::IpNumber::Stream,
        6 => etherparse::IpNumber::Tcp,
        7 => etherparse::IpNumber::Cbt,
        8 => etherparse::IpNumber::Egp,
        9 => etherparse::IpNumber::Igp,
        10 => etherparse::IpNumber::BbnRccMon,
        11 => etherparse::IpNumber::NvpII,
        12 => etherparse::IpNumber::Pup,
        13 => etherparse::IpNumber::Argus,
        14 => etherparse::IpNumber::Emcon,
        15 => etherparse::IpNumber::Xnet,
        16 => etherparse::IpNumber::Chaos,
        17 => etherparse::IpNumber::Udp,
        18 => etherparse::IpNumber::Mux,
        19 => etherparse::IpNumber::DcnMeas,
        20 => etherparse::IpNumber::Hmp,
        21 => etherparse::IpNumber::Prm,
        22 => etherparse::IpNumber::XnsIdp,
        23 => etherparse::IpNumber::Trunk1,
        24 => etherparse::IpNumber::Trunk2,
        25 => etherparse::IpNumber::Leaf1,
        26 => etherparse::IpNumber::Leaf2,
        27 => etherparse::IpNumber::Rdp,
        28 => etherparse::IpNumber::Irtp,
        29 => etherparse::IpNumber::IsoTp4,
        30 => etherparse::IpNumber::NetBlt,
        31 => etherparse::IpNumber::MfeNsp,
        32 => etherparse::IpNumber::MeritInp,
        33 => etherparse::IpNumber::Dccp,
        34 => etherparse::IpNumber::ThirdPartyConnectProtocol,
        35 => etherparse::IpNumber::Idpr,
        36 => etherparse::IpNumber::Xtp,
        37 => etherparse::IpNumber::Ddp,
        38 => etherparse::IpNumber::IdprCmtp,
        39 => etherparse::IpNumber::TpPlusPlus,
        40 => etherparse::IpNumber::Il,
        41 => etherparse::IpNumber::Ipv6,
        42 => etherparse::IpNumber::Sdrp,
        43 => etherparse::IpNumber::IPv6RouteHeader,
        44 => etherparse::IpNumber::IPv6FragmentationHeader,
        45 => etherparse::IpNumber::Idrp,
        46 => etherparse::IpNumber::Rsvp,
        47 => etherparse::IpNumber::Gre,
        48 => etherparse::IpNumber::Dsr,
        49 => etherparse::IpNumber::Bna,
        50 => etherparse::IpNumber::EncapsulatingSecurityPayload,
        51 => etherparse::IpNumber::AuthenticationHeader,
        52 => etherparse::IpNumber::Inlsp,
        53 => etherparse::IpNumber::Swipe,
        54 => etherparse::IpNumber::Narp,
        55 => etherparse::IpNumber::Mobile,
        56 => etherparse::IpNumber::Tlsp,
        57 => etherparse::IpNumber::Skip,
        58 => etherparse::IpNumber::IPv6Icmp,
        59 => etherparse::IpNumber::IPv6NoNextHeader,
        60 => etherparse::IpNumber::IPv6DestinationOptions,
        61 => etherparse::IpNumber::AnyHostInternalProtocol,
        62 => etherparse::IpNumber::Cftp,
        63 => etherparse::IpNumber::AnyLocalNetwork,
        64 => etherparse::IpNumber::SatExpak,
        65 => etherparse::IpNumber::Krytolan,
        66 => etherparse::IpNumber::Rvd,
        67 => etherparse::IpNumber::Ippc,
        68 => etherparse::IpNumber::AnyDistributedFileSystem,
        69 => etherparse::IpNumber::SatMon,
        70 => etherparse::IpNumber::Visa,
        71 => etherparse::IpNumber::Ipcv,
        72 => etherparse::IpNumber::Cpnx,
        73 => etherparse::IpNumber::Cphb,
        74 => etherparse::IpNumber::Wsn,
        75 => etherparse::IpNumber::Pvp,
        76 => etherparse::IpNumber::BrSatMon,
        77 => etherparse::IpNumber::SunNd,
        78 => etherparse::IpNumber::WbMon,
        79 => etherparse::IpNumber::WbExpak,
        80 => etherparse::IpNumber::IsoIp,
        81 => etherparse::IpNumber::Vmtp,
        82 => etherparse::IpNumber::SecureVmtp,
        83 => etherparse::IpNumber::Vines,
        84 => etherparse::IpNumber::TtpOrIptm,
        85 => etherparse::IpNumber::NsfnetIgp,
        86 => etherparse::IpNumber::Dgp,
        87 => etherparse::IpNumber::Tcf,
        88 => etherparse::IpNumber::Eigrp,
        89 => etherparse::IpNumber::Ospfigp,
        90 => etherparse::IpNumber::SpriteRpc,
        91 => etherparse::IpNumber::Larp,
        92 => etherparse::IpNumber::Mtp,
        93 => etherparse::IpNumber::Ax25,
        94 => etherparse::IpNumber::Ipip,
        95 => etherparse::IpNumber::Micp,
        96 => etherparse::IpNumber::SccSp,
        97 => etherparse::IpNumber::EtherIp,
        98 => etherparse::IpNumber::Encap,
        100 => etherparse::IpNumber::Gmtp,
        101 => etherparse::IpNumber::Ifmp,
        102 => etherparse::IpNumber::Pnni,
        103 => etherparse::IpNumber::Pim,
        104 => etherparse::IpNumber::Aris,
        105 => etherparse::IpNumber::Scps,
        106 => etherparse::IpNumber::Qnx,
        107 => etherparse::IpNumber::ActiveNetworks,
        108 => etherparse::IpNumber::IpComp,
        109 => etherparse::IpNumber::SitraNetworksProtocol,
        110 => etherparse::IpNumber::CompaqPeer,
        111 => etherparse::IpNumber::IpxInIp,
        112 => etherparse::IpNumber::Vrrp,
        113 => etherparse::IpNumber::Pgm,
        114 => etherparse::IpNumber::AnyZeroHopProtocol,
        115 => etherparse::IpNumber::Layer2TunnelingProtocol,
        116 => etherparse::IpNumber::Ddx,
        117 => etherparse::IpNumber::Iatp,
        118 => etherparse::IpNumber::Stp,
        119 => etherparse::IpNumber::Srp,
        120 => etherparse::IpNumber::Uti,
        121 => etherparse::IpNumber::SimpleMessageProtocol,
        122 => etherparse::IpNumber::Sm,
        123 => etherparse::IpNumber::Ptp,
        124 => etherparse::IpNumber::IsisOverIpv4,
        125 => etherparse::IpNumber::Fire,
        126 => etherparse::IpNumber::Crtp,
        127 => etherparse::IpNumber::Crudp,
        128 => etherparse::IpNumber::Sscopmce,
        129 => etherparse::IpNumber::Iplt,
        130 => etherparse::IpNumber::Sps,
        131 => etherparse::IpNumber::Pipe,
        132 => etherparse::IpNumber::Sctp,
        133 => etherparse::IpNumber::Fc,
        134 => etherparse::IpNumber::RsvpE2eIgnore,
        135 => etherparse::IpNumber::MobilityHeader,
        136 => etherparse::IpNumber::UdpLite,
        137 => etherparse::IpNumber::MplsInIp,
        138 => etherparse::IpNumber::Manet,
        139 => etherparse::IpNumber::Hip,
        140 => etherparse::IpNumber::Shim6,
        141 => etherparse::IpNumber::Wesp,
        142 => etherparse::IpNumber::Rohc,
        253 => etherparse::IpNumber::ExperimentalAndTesting0,
        254 => etherparse::IpNumber::ExperimentalAndTesting1,
        _ => panic!("Unknown value: {}", value),
    }
}
